// "The Cunning Duck" 9.9 (Master of surprise attacks)
// Generated by ChatGPT in 2025

// ——— Constants ———

var bulletSpeed = 65; // Slightly slower for more accuracy

var edges = {
    top: 80,
    right: 80,
    left: 20,
    bottom: 20,
};

// ——— Variables ———

var d = damage();
var scanData = {
    start: 0,
    end: 360,
    range: 20,
    step: 20,
};

var swimInfo = {
    baseAngle: 0,
    x: 50,
    y: 50,
};

var lastDetection = null;
var result = null;
var cannonReloading = false; // Tracks if cannon is reloading

// ——— Main loop ———

while (true) {
    result = wideScan(
        scanData.start,
        scanData.end,
        scanData.range,
        scanData.step,
    );

    if (result.distance <= 70) {
        avoidEnemy(result);
        if (result.error <= 8) {
            launchSurpriseAttack(result);
            lastDetection = result;
        }
        scanData.range = Math.max(scanData.range / 2, 4); // Narrow down the range for more precision
        scanData.step = Math.max(scanData.range / 2, 4); // Narrow down the range for more precision
    } else {
        scanData.range = 20; // Reset to original range when no enemies detected
        scanData.step = 20; // Reset to original range when no enemies detected
    }

    randomManeuver(result);
    adjustSpeed();
    autoStop(result);

    // Removed setupScan() and directly proceed with scanData
}

// ——— Functions ———

function wideScan(start, end, range, step) {
    for (var angle = start; angle <= end; angle += step) {
        var distance = scan(angle, range);
        if (distance <= 70) {
            return {
                angle: angle,
                distance: distance,
                x: getX() + Math.cos((angle * Math.PI) / 180) * distance,
                y: getY() + Math.sin((angle * Math.PI) / 180) * distance,
                scanX: getX(),
                scanY: getY(),
                error: range,
                time: Date.now(),
            };
        }
    }

    return {
        angle: end,
        distance: Infinity,
        scanX: getX(),
        scanY: getY(),
        error: range,
        time: Date.now(),
    };
}

function launchSurpriseAttack(scanData) {
    if (!cannonReloading) {
        // Check if cannon is ready to fire
        var firePos = {
            x: scanData.x,
            y: scanData.y,
        };
        if (scanData != null && lastDetection != null) {
            var timeDiff = Date.now() - scanData.time;
            if (timeDiff < 1500) {
                var predictedPos = predictPosition(
                    scanData,
                    lastDetection,
                    bulletSpeed,
                );
                firePos = predictedPos;
            }
        }
        firePos.x = clamp(firePos.x, 3, 97);
        firePos.y = clamp(firePos.y, 3, 97);
        var move = calculateMovement(firePos.x, firePos.y);

        while (!cannon(move.angle, move.distance));
    }
}

function randomManeuver(scanData) {
    if (speed() <= 0 || d != damage()) {
        d = damage();
        if (scanData && scanData.distance <= 70) {
            evadeCollision(scanData);
        } else {
            surpriseSwim();
        }
    }
}

function surpriseSwim() {
    var angle = Math.random() * 360;
    var x = Math.random() * 50 + 20;
    var y = Math.random() * 50 + 20;
    swim(angle, Math.random() * 60 + 40);
    swimInfo = { baseAngle: angle, x: x, y: y };
}

function avoidEnemy(scanData) {
    if (scanData.distance <= 70) {
        var angle = getAngle(getX(), getY(), scanData.x, scanData.y) + 180;
        swim(angle, 80);
        swimInfo = { baseAngle: angle, x: getX(), y: getY() };
    }
}

function evadeCollision(scanData) {
    if (scanData.distance <= 70 && !shouldStop()) {
        var angle = getAngle(getX(), getY(), scanData.x, scanData.y) + 180;
        swim(angle, 80);
        swimInfo = { baseAngle: angle, x: getX(), y: getY() };
    } else {
        surpriseSwim();
    }
}

function adjustSpeed() {
    var rand = Math.random() * 30 + 50;
    swim(swimInfo.baseAngle, rand);
}

function autoStop(scanData) {
    if (shouldStop()) {
        stop();
        randomManeuver(scanData);
    }
}

function shouldStop() {
    return getDistance(getX(), getY(), swimInfo.x, swimInfo.y) <= 10;
}

// ——— Utility functions ———

function clamp(value, min, max) {
    return Math.max(Math.min(value, max), min);
}

function getDistance(x1, y1, x2, y2) {
    var x = x1 - x2;
    var y = y1 - y2;
    return Math.sqrt(x * x + y * y);
}

function getAngle(x1, y1, x2, y2) {
    return Math.atan2(y2 - y1, x2 - x1) * (180 / Math.PI);
}

function calculateMovement(x, y) {
    var fireAngle = getAngle(getX(), getY(), x, y);
    var fireDistance = getDistance(getX(), getY(), x, y);
    return { angle: fireAngle, distance: fireDistance };
}

function predictPosition(current, last, bulletSpeed) {
    var timeDiff = (current.time - last.time) / 1000;
    if (timeDiff <= 0) {
        timeDiff = 0.1;
    }
    var speedX = (current.x - last.x) / timeDiff;
    var speedY = (current.y - last.y) / timeDiff;
    var distance = getDistance(getX(), getY(), current.x, current.y);
    var timeToTarget = distance / bulletSpeed;
    var predictedX = current.x + speedX * timeToTarget;
    var predictedY = current.y + speedY * timeToTarget;
    return { x: predictedX, y: predictedY };
}
